apiVersion: v1
data:
  k8config-sync.sh: |+
    #!/bin/bash
    set -x
    FULLURL={{ .Values.clouddriver.dynGit.uri }}
    URL=${FULLURL#https://}  # Remove the leading https://
    REPO=${URL##*/}  # Get the repo-name
    REPO=${REPO%.git}  # Removing training .git, if present
    mkdir -p /opsmx
    rm -rf $REPO
    echo " ####### Cloning the Dynamic Account Repo #################"
    git clone  -c http.sslVerify=false https://{{ .Values.clouddriver.dynGit.username }}:{{ .Values.clouddriver.dynGit.password }}@$URL
    cd $REPO
      cat clouddriver-local.yml |grep -i opsmx |awk '{print $2}' |tr -d '"' | awk 'BEGIN{FS="/opsmx/"}{print $2}' > /opsmx/config_files.txt
    for config in $(cat /opsmx/config_files.txt)
    do
    kubectl get secrets $config -o=jsonpath='{.data.*}'|base64 -d > /opsmx/$config
    #cp -pr /opsmx/$config /tmp/config-repo/
    done
kind: ConfigMap
metadata:
  name: k8config-sync
