apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding  # ClusterRoleBinding, if we have access accross the cluster
metadata:
  name: clouddriver-default-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role             # ClusteRoleBinding if we have access accross the cluster
  name: clouddriver-default-role   # cluster-admin if we have the access
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  # Clouddriver does not currently allow config of its
  # service account.
  name: default
