apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: create-agent-{{ .Values.agent.agentName }}
rules:
  - apiGroups: ['']
    resources: ['*']
    verbs: [ '*' ]
  - apiGroups: ['rbac.authorization.k8s.io' ]
    resources: [ '*' ]
    verbs: [ '*' ]
  - apiGroups: ['autoscaling']
    resources: ['horizontalpodautoscalers']
    verbs: ['list', 'get']
  - apiGroups: ['apps']
    resources: ['controllerrevisions', 'statefulsets']
    verbs: ['list']
  - apiGroups: ['extensions', 'apps']
    resources: ['deployments', 'replicasets', 'ingresses']
    verbs:
      [
        'create',
        'delete',
        'deletecollection',
        'get',
        'list',
        'patch',
        'update',
        'watch',
      ]
